#include "ui.h"
#include <cmath>

/**
 * Checks if the return data from a heuristic is valid.
 * @param data Struct containing the data generated by the heuristic.
*/
bool isInvalid(ReturnDataTSP data)
{
	return data.processingTime == -1 || data.distances.empty() 
		|| data.stops.empty() || data.totalDistance == -1;
}

/**
 * Shows the route calculated by a specific heuristic for the currently loaded type.
 * @param type Heuristic type.
*/
void UI::resultMenu(HeuristicType type)
{
	ReturnDataTSP ret = manager.tspCaller(type);

	if (isInvalid(ret))
	{
		showMessage("AN ERROR OCCURRED!", "The heuristic returned invalid data.");
		return;
	}

	size_t count = 0;
	while (1)
	{
		CLEAR;
		std::cout 
		<< "Results for heuristic " << type << "\n"
		<< "\n";

		size_t i = count;
		if (i != 0) std::cout << "("<< i << " ENTRIES ABOVE)\n...\n↓\n";

		for (; i < std::min(count + 5, ret.stops.size() - 1); i++)
		{
			std::cout
			<< ret.stops[i] << "\n"
			<< "↓ " << ret.distances[i] << "km\n";
		}
		std::cout << ret.stops[i] << "\n";
		if (i != ret.stops.size() - 1) std::cout << "↓\n...\n("<< ret.stops.size() - i << " ENTRIES BELOW)\n";

		std::cout
		<< "\n" 
		<< "Total Stops: " << ret.stops.size() - 2 << " (" << ret.stops.size() << " stops including the initial/final point)\n"
		<< "Total Distance Travelled: " << ret.totalDistance << "km\n"
		<< "Time taken to run the heuristic: " << ret.processingTime << "s\n"
		<< "\n"
		<< "[S] - Push list down\t[W] - Push list up\n"
		<< "[B] - Back \t\t[Q] - Exit\n"
		<< "\n"
        << "$> ";

		std::string str;
		std::getline(std::cin, str);

		if (str == "b" || str == "B") return;

		if (str == "q" || str == "Q")
		{
			CLEAR;
			exit(0);
		}

		if (str == "s" || str == "S")
		{
			count = count + 5 < ret.stops.size() - 1 ? count + 5 : count;
			continue;
		}

		if (str == "w" || str == "W")
		{
			count = count < 5 ? 0 : count - 5;
			continue;
		}
	}
}
